AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: An AWS Serverless Application Model template describing your function.
Resources:
  Gettoken:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: sample_lambda_function-dev
      ImageUri: 385240549448.dkr.ecr.us-east-1.amazonaws.com/demo_repo:node_todo_app
      Description: ''
      MemorySize: 128
      Timeout: 600
      Architectures:
        - x86_64
      EphemeralStorage:
        Size: 512
      EventInvokeConfig:
        MaximumEventAgeInSeconds: 21600
        MaximumRetryAttempts: 2
      #Layers:
        #- arn:aws:lambda:ap-south-1:339713002425:layer:axios:2
        #- arn:aws:lambda:ap-south-1:339713002425:layer:qs:2
      PackageType: Image
      Role: 'arn:aws:iam::385240549448:role/service-role/sample_lambda_function-role-dh3qlg4h'
